# Site settings
title: My personal blog about cibersecurity
description: Personal blog about cibersecurity, scripts and more!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: xaxxjs
user_description: I'm passionate about cybersecurity, scripting and I am currently eJPT certified
user_title: Cybersecurity Enthusiast
email: trabajosandujar11@gmail.com
twitter_username: sergioab7
github_username:  sergioab7
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
